server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:EmployeeRecord
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  devtools:
    restart:
      enabled: true
