INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (1, 'HARI', 'KANNA', 'HARI@GMAIL.COM');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (2, 'VINAY', 'MYAKALA', 'VINAY@GMAIL.COM');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (3, 'SHIVA', 'GURRALA', 'SHIVA@YAHOO.COM');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (4, 'VINOD', 'KYATHAM', 'VINOD@HOTMAIL.COM');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (5, 'SUMANTH', 'KUNTA', 'SUMANTH@OUTLOOK.COM');

